// admin-panel/components/layout/sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import {
  LayoutDashboard,
  Users,
  Building2,
  CreditCard,
  MessageSquare,
  Star,
  Database,
  BarChart3,
  LogOut,
  Home,
  Settings,
} from 'lucide-react';
import { logoutAction } from '@/app/actions/auth';

const navItems = [
  { href: '/', label: 'Dashboard', icon: LayoutDashboard },
  { href: '/users', label: 'Users', icon: Users },
  { href: '/properties', label: 'Properties', icon: Building2 },
  { href: '/subscriptions', label: 'Subscriptions', icon: CreditCard },
  { href: '/inquiries', label: 'Inquiries', icon: MessageSquare },
  { href: '/reviews', label: 'Reviews', icon: Star },
  { href: '/analytics', label: 'Analytics', icon: BarChart3 },
  { href: '/platform-data', label: 'Platform Data', icon: Database },
];

export function Sidebar() {
  const pathname = usePathname();

  return (
    <aside className="w-64 bg-gray-950 border-r border-gray-800 flex flex-col h-screen fixed left-0 top-0 z-30">
      {/* Logo */}
      <div className="px-6 py-5 border-b border-gray-800">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-[#FF6B35] flex items-center justify-center">
            <Home className="w-5 h-5 text-white" />
          </div>
          <div>
            <p className="text-white font-bold text-sm leading-tight">NxtGen</p>
            <p className="text-[#FF6B35] text-xs font-medium">Admin Panel</p>
          </div>
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex-1 px-3 py-4 overflow-y-auto">
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider px-3 mb-2">
          Main Menu
        </p>
        <ul className="space-y-0.5">
          {navItems.map(({ href, label, icon: Icon }) => {
            const isActive = href === '/' ? pathname === '/' : pathname.startsWith(href);
            return (
              <li key={href}>
                <Link
                  href={href}
                  className={cn(
                    'flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all',
                    isActive
                      ? 'bg-[#FF6B35]/10 text-[#FF6B35] border border-[#FF6B35]/20'
                      : 'text-gray-400 hover:text-white hover:bg-gray-800'
                  )}
                >
                  <Icon className="w-4.5 h-4.5 flex-shrink-0" size={18} />
                  {label}
                </Link>
              </li>
            );
          })}
        </ul>
      </nav>

      {/* Bottom: Logout */}
      <div className="px-3 py-4 border-t border-gray-800">
        <form action={logoutAction}>
          <button
            type="submit"
            className="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium text-gray-400 hover:text-red-400 hover:bg-red-400/10 transition-all w-full"
          >
            <LogOut size={18} />
            Sign Out
          </button>
        </form>
      </div>
    </aside>
  );
}

// admin-panel/src/lib/components/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import {
    LayoutDashboard,
    Building2,
    Users,
    Flag,
    BadgeCheck,
    CreditCard,
    Database,
    BarChart3,
    Home,
  } from 'lucide-svelte';

  const nav = [
    { href: '/', label: 'Dashboard', icon: LayoutDashboard },
    { href: '/listings', label: 'Listings', icon: Building2 },
    { href: '/users', label: 'Users', icon: Users },
    { href: '/verifications', label: 'Verifications', icon: BadgeCheck },
    { href: '/reports', label: 'Reports', icon: Flag },
    { href: '/subscriptions', label: 'Subscriptions', icon: CreditCard },
    { href: '/platform-data', label: 'Platform Data', icon: Database },
    { href: '/analytics', label: 'Analytics', icon: BarChart3 },
  ];

  const active = (href: string, path: string) =>
    href === '/' ? path === '/' : path.startsWith(href);
</script>

<aside class="sticky top-0 hidden h-screen w-64 shrink-0 border-r border-line bg-panel/60 p-4 backdrop-blur md:block">
  <div class="mb-8 flex items-center gap-2 px-2">
    <div class="grid h-9 w-9 place-items-center rounded-xl bg-primary">
      <Home size={18} color="#fff" />
    </div>
    <div>
      <div class="text-sm font-extrabold leading-none text-white">NxtGen</div>
      <div class="text-[11px] text-gold">Admin</div>
    </div>
  </div>

  <nav class="space-y-1">
    {#each nav as item}
      {@const isActive = active(item.href, $page.url.pathname)}
      <a
        href={item.href}
        class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors {isActive
          ? 'bg-primary/15 text-primary'
          : 'text-slate-400 hover:bg-panel2 hover:text-slate-200'}"
      >
        <item.icon size={18} />
        {item.label}
        {#if isActive}
          <span class="ml-auto h-1.5 w-1.5 rounded-full bg-primary"></span>
        {/if}
      </a>
    {/each}
  </nav>
</aside>
