// admin-panel/app/(admin)/subscriptions/page.tsx
export const dynamic = 'force-dynamic';
import { createAdminClient } from '@/lib/supabase/server';
import { Topbar } from '@/components/layout/topbar';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { SubscriptionActions } from '@/components/subscriptions/subscription-actions';
import { formatDate, formatDateTime } from '@/lib/utils';
import { CreditCard } from 'lucide-react';

async function getSubscriptions(plan?: string, status?: string) {
  const supabase = createAdminClient();
  let query = supabase
    .from('subscriptions')
    .select('*, user:user_id(name, email, phone)')
    .order('created_at', { ascending: false })
    .limit(200);

  if (plan && plan !== 'all') query = query.eq('plan', plan);
  if (status && status !== 'all') query = query.eq('status', status);

  const { data } = await query;
  return data || [];
}

export default async function SubscriptionsPage({
  searchParams,
}: {
  searchParams: Promise<{ plan?: string; status?: string }>;
}) {
  const params = await searchParams;
  const subs = await getSubscriptions(params.plan, params.status);

  const counts = subs.reduce(
    (acc, s) => {
      acc[s.status] = (acc[s.status] || 0) + 1;
      acc[s.plan] = (acc[s.plan] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  return (
    <div>
      <Topbar title="Subscriptions" subtitle={`${subs.length} subscriptions`} />

      <div className="p-6 space-y-6">
        {/* Stats */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
          {[
            { key: 'active', label: 'Active', variant: 'success' as const },
            { key: 'expired', label: 'Expired', variant: 'danger' as const },
            { key: 'cancelled', label: 'Cancelled', variant: 'secondary' as const },
            { key: 'free', label: 'Free Plan', variant: 'secondary' as const },
            { key: 'silver', label: 'Silver Plan', variant: 'info' as const },
            { key: 'gold', label: 'Gold Plan', variant: 'warning' as const },
          ].map(({ key, label }) => (
            <Card key={key} className="p-4">
              <p className="text-2xl font-bold text-white">{counts[key] || 0}</p>
              <p className="text-xs text-gray-500 mt-1">{label}</p>
            </Card>
          ))}
        </div>

        {/* Filters */}
        <Card className="p-4">
          <form className="flex flex-wrap gap-3">
            <select name="plan" defaultValue={params.plan || 'all'} className="rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-[#FF6B35]">
              <option value="all">All Plans</option>
              <option value="free">Free</option>
              <option value="silver">Silver</option>
              <option value="gold">Gold</option>
            </select>
            <select name="status" defaultValue={params.status || 'all'} className="rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-[#FF6B35]">
              <option value="all">All Status</option>
              <option value="active">Active</option>
              <option value="expired">Expired</option>
              <option value="cancelled">Cancelled</option>
            </select>
            <button type="submit" className="px-4 py-2 bg-[#FF6B35] text-white text-sm rounded-lg hover:bg-[#e55a25] transition-colors">
              Filter
            </button>
          </form>
        </Card>

        {/* Table */}
        <Card className="p-0 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-800">
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">User</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Plan</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Starts</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Expires</th>
                  <th className="text-right px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                {subs.map((s: any) => (
                  <tr key={s.id} className="hover:bg-gray-800/50 transition-colors">
                    <td className="px-6 py-4">
                      <p className="text-sm font-medium text-white">{s.user?.name || '—'}</p>
                      <p className="text-xs text-gray-500">{s.user?.email || ''}</p>
                    </td>
                    <td className="px-6 py-4">
                      <Badge variant={s.plan === 'gold' ? 'warning' : s.plan === 'silver' ? 'info' : 'secondary'}>
                        {s.plan}
                      </Badge>
                    </td>
                    <td className="px-6 py-4">
                      <Badge variant={s.status === 'active' ? 'success' : s.status === 'expired' ? 'danger' : 'secondary'}>
                        {s.status}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-400">{formatDate(s.starts_at)}</td>
                    <td className="px-6 py-4 text-sm text-gray-400">{formatDate(s.ends_at)}</td>
                    <td className="px-6 py-4 text-right">
                      <SubscriptionActions subscriptionId={s.id} status={s.status} />
                    </td>
                  </tr>
                ))}
                {subs.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-6 py-12 text-center">
                      <CreditCard className="w-10 h-10 text-gray-700 mx-auto mb-3" />
                      <p className="text-gray-500 text-sm">No subscriptions found</p>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </Card>
      </div>
    </div>
  );
}

// admin-panel/src/routes/(app)/subscriptions/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import Topbar from '$lib/components/Topbar.svelte';
  import Card from '$lib/components/Card.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import { formatDate } from '$lib/format';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  const tone = (s: string) => (s === 'active' ? 'success' : s === 'cancelled' ? 'neutral' : 'warning');
  const planTone = (p: string) => (p === 'gold' ? 'gold' : p === 'silver' ? 'info' : 'neutral');
</script>

<Topbar title="Subscriptions" subtitle={`${data.items.length} total`} name={data.session?.name ?? 'Admin'} />

<div class="space-y-5 p-6">
  <form method="GET" class="flex gap-3">
    <select name="status" value={data.filters.status} class="input max-w-[200px]">
      <option value="">All statuses</option><option value="active">Active</option>
      <option value="cancelled">Cancelled</option><option value="expired">Expired</option>
    </select>
    <button class="btn-primary">Filter</button>
  </form>

  <Card class="p-0 overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="border-b border-line text-left text-xs uppercase tracking-wider text-slate-500">
          <tr><th class="px-5 py-3">User</th><th class="px-5 py-3">Plan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Ends</th><th class="px-5 py-3 text-right">Actions</th></tr>
        </thead>
        <tbody class="divide-y divide-line">
          {#each data.items as s}
            <tr class="hover:bg-panel2/50">
              <td class="px-5 py-3"><div class="font-medium text-slate-100">{s.user?.name ?? '—'}</div><div class="text-xs text-slate-500">{s.user?.email ?? ''}</div></td>
              <td class="px-5 py-3"><Badge tone={planTone(s.plan)}>{s.plan}</Badge></td>
              <td class="px-5 py-3"><Badge tone={tone(s.status)}>{s.status}</Badge></td>
              <td class="px-5 py-3 text-slate-400">{formatDate(s.endsAt)}</td>
              <td class="px-5 py-3">
                <div class="flex items-center justify-end gap-2">
                  <form method="POST" action="?/extend" use:enhance class="flex items-center gap-1">
                    <input type="hidden" name="id" value={s.id} />
                    <input name="days" type="number" min="1" max="730" value="30" class="input w-20 py-1.5" />
                    <button class="btn-ghost px-3 py-1.5 text-xs">Extend</button>
                  </form>
                  {#if s.status === 'active'}
                    <form method="POST" action="?/cancel" use:enhance>
                      <input type="hidden" name="id" value={s.id} />
                      <button class="btn-ghost px-3 py-1.5 text-xs">Cancel</button>
                    </form>
                  {/if}
                </div>
              </td>
            </tr>
          {/each}
          {#if data.items.length === 0}<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No subscriptions</td></tr>{/if}
        </tbody>
      </table>
    </div>
  </Card>
</div>
