// admin-panel/app/login/page.tsx
'use client';

import { useActionState, useState, useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import { loginAction } from '@/app/actions/auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Home, Shield, Eye, EyeOff } from 'lucide-react';
import { getSupabaseClient } from '@/lib/supabase/client';

export default function LoginPage() {
  const searchParams = useSearchParams();
  const isRecovery = searchParams.get('type') === 'recovery' && searchParams.get('token');
  
  const [state, action, pending] = useActionState(loginAction, undefined);
  const [showPassword, setShowPassword] = useState(false);
  const [resetPassword, setResetPassword] = useState('');
  const [resetConfirm, setResetConfirm] = useState('');
  const [resetError, setResetError] = useState('');
  const [resetSuccess, setResetSuccess] = useState(false);
  const [resetting, setResetting] = useState(false);

  const handlePasswordReset = async (e: React.FormEvent) => {
    e.preventDefault();
    setResetting(true);
    setResetError('');

    if (resetPassword !== resetConfirm) {
      setResetError('Passwords do not match');
      setResetting(false);
      return;
    }

    if (resetPassword.length < 8) {
      setResetError('Password must be at least 8 characters');
      setResetting(false);
      return;
    }

    try {
      const supabase = getSupabaseClient();
      const token = searchParams.get('token');

      const { error } = await supabase.auth.updateUser({ password: resetPassword });

      if (error) throw error;

      setResetSuccess(true);
      setResetPassword('');
      setResetConfirm('');
      setTimeout(() => {
        window.location.href = '/login';
      }, 2000);
    } catch (err: any) {
      setResetError(err.message || 'Failed to reset password');
    } finally {
      setResetting(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-linear-to-br from-[#FF6B35]/5 via-transparent to-transparent pointer-events-none" />

      <div className="w-full max-w-md">
        <div className="flex flex-col items-center mb-8">
          <div className="w-14 h-14 rounded-2xl bg-[#FF6B35] flex items-center justify-center mb-4 shadow-lg shadow-[#FF6B35]/30">
            <Home className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-2xl font-bold text-white">NxtGenProperties</h1>
          <p className="text-gray-500 text-sm mt-1">Admin Portal</p>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8">
          <div className="flex items-center gap-2 mb-6">
            <Shield className="w-5 h-5 text-[#FF6B35]" />
            <h2 className="text-lg font-semibold text-white">
              {isRecovery ? 'Set Your Password' : 'Secure Admin Login'}
            </h2>
          </div>

          {isRecovery ? (
            <form onSubmit={handlePasswordReset} className="space-y-4">
              <div className="flex flex-col gap-1">
                <label htmlFor="password" className="text-sm font-medium text-gray-300">
                  New Password
                </label>
                <div className="relative">
                  <input
                    id="password"
                    type={showPassword ? 'text' : 'password'}
                    placeholder="••••••••"
                    value={resetPassword}
                    onChange={(e) => setResetPassword(e.target.value)}
                    required
                    className="w-full rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 pr-10 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#FF6B35] focus:border-transparent"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300"
                  >
                    {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <label htmlFor="confirm" className="text-sm font-medium text-gray-300">
                  Confirm Password
                </label>
                <input
                  id="confirm"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  value={resetConfirm}
                  onChange={(e) => setResetConfirm(e.target.value)}
                  required
                  className="w-full rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#FF6B35] focus:border-transparent"
                />
              </div>

              {resetError && (
                <div className="flex items-center gap-2 bg-red-900/30 border border-red-800 rounded-lg px-3 py-2.5">
                  <Shield className="w-4 h-4 text-red-400 shrink-0" />
                  <p className="text-red-400 text-sm">{resetError}</p>
                </div>
              )}

              {resetSuccess && (
                <div className="flex items-center gap-2 bg-green-900/30 border border-green-800 rounded-lg px-3 py-2.5">
                  <Shield className="w-4 h-4 text-green-400 shrink-0" />
                  <p className="text-green-400 text-sm">Password set successfully! Redirecting...</p>
                </div>
              )}

              <Button type="submit" className="w-full mt-2" loading={resetting} size="lg">
                Set Password & Login
              </Button>
            </form>
          ) : (
            <form action={action} className="space-y-4">
            <Input
              id="email"
              name="email"
              type="email"
              label="Email Address"
              placeholder="admin@nxtgenproperties.com"
              required
              autoComplete="email"
            />

            <div className="flex flex-col gap-1">
              <label htmlFor="password" className="text-sm font-medium text-gray-300">
                Password
              </label>
              <div className="relative">
                <input
                  id="password"
                  name="password"
                  type={showPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  required
                  autoComplete="current-password"
                  className="w-full rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 pr-10 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#FF6B35] focus:border-transparent"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300"
                >
                  {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
            </div>

            {state?.error && (
              <div className="flex items-center gap-2 bg-red-900/30 border border-red-800 rounded-lg px-3 py-2.5">
                <Shield className="w-4 h-4 text-red-400 shrink-0" />
                <p className="text-red-400 text-sm">{state.error}</p>
              </div>
            )}

            <Button type="submit" className="w-full mt-2" loading={pending} size="lg">
              Sign In to Admin Panel
            </Button>
            </form>
          )}

          <p className="text-center text-xs text-gray-600 mt-6">
            Protected by JWT session authentication
          </p>
        </div>

        <p className="text-center text-xs text-gray-700 mt-4">
          NxtGenProperties {new Date().getFullYear()} · Admin Portal v1.0
        </p>
      </div>
    </div>
  );
}

// nxt-web/src/routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { auth } from '$lib/stores/auth.svelte';
	import { ApiError } from '$lib/api/client';
	import AuthShell from '$lib/components/AuthShell.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import Mail from '@lucide/svelte/icons/mail';
	import Lock from '@lucide/svelte/icons/lock';

	let email = $state('');
	let password = $state('');
	let loading = $state(false);
	let error = $state('');

	const redirect = $derived(page.url.searchParams.get('redirect') || '/dashboard');

	async function submit() {
		error = '';
		loading = true;
		try {
			await auth.login(email.trim(), password);
			goto(redirect);
		} catch (e) {
			error = e instanceof ApiError ? e.message : 'Something went wrong. Try again.';
		} finally {
			loading = false;
		}
	}

	function demo(role: 'owner' | 'broker') {
		email = `${role}1@example.com`;
		password = 'Password123!';
	}
</script>

<svelte:head><title>Sign in — NxtGenProperties</title></svelte:head>

<AuthShell title="Welcome back" subtitle="Sign in to manage listings, favorites and inquiries.">
	<form onsubmit={(e) => { e.preventDefault(); submit(); }} class="space-y-4">
		{#if error}
			<p class="rounded-xl bg-error/10 px-4 py-3 text-sm font-medium text-error">{error}</p>
		{/if}

		<label class="block">
			<span class="mb-1.5 block text-sm font-semibold text-navy">Email</span>
			<div class="relative">
				<Mail class="pointer-events-none absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-ink-soft" />
				<Input bind:value={email} type="email" placeholder="you@email.com" required class="pl-11" />
			</div>
		</label>

		<label class="block">
			<span class="mb-1.5 block text-sm font-semibold text-navy">Password</span>
			<div class="relative">
				<Lock class="pointer-events-none absolute left-3.5 top-1/2 size-4.5 -translate-y-1/2 text-ink-soft" />
				<Input bind:value={password} type="password" placeholder="••••••••" required class="pl-11" />
			</div>
		</label>

		<Button type="submit" class="w-full" size="lg" {loading}>Sign in</Button>
	</form>

	<div class="mt-5 rounded-xl border border-dashed border-outline-soft bg-card p-4 text-sm">
		<p class="font-semibold text-navy">Demo accounts</p>
		<p class="mt-1 text-ink-soft">Password: <code class="rounded bg-surface px-1.5 py-0.5 text-xs">Password123!</code></p>
		<div class="mt-2 flex gap-2">
			<button class="rounded-full bg-surface px-3 py-1 text-xs font-semibold text-primary" onclick={() => demo('owner')}>Owner</button>
			<button class="rounded-full bg-surface px-3 py-1 text-xs font-semibold text-primary" onclick={() => demo('broker')}>Broker</button>
		</div>
	</div>

	<p class="mt-6 text-center text-sm text-ink-soft">
		New to NxtGen? <a href="/register" class="font-semibold text-primary hover:underline">Create an account</a>
	</p>
</AuthShell>
