// admin-panel/components/ui/button.tsx
import { cn } from '@/lib/utils';
import { ButtonHTMLAttributes, forwardRef } from 'react';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
}

const variants = {
  primary: 'bg-[#FF6B35] hover:bg-[#e55a25] text-white',
  secondary: 'bg-gray-800 hover:bg-gray-700 text-white',
  danger: 'bg-red-600 hover:bg-red-700 text-white',
  ghost: 'bg-transparent hover:bg-gray-800 text-gray-300',
  outline: 'border border-gray-600 hover:bg-gray-800 text-gray-300',
};

const sizes = {
  sm: 'px-3 py-1.5 text-xs',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
};

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = 'primary', size = 'md', loading, disabled, children, ...props }, ref) => {
    return (
      <button
        ref={ref}
        disabled={disabled || loading}
        className={cn(
          'inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-[#FF6B35] focus:ring-offset-2 focus:ring-offset-gray-900 disabled:opacity-50 disabled:cursor-not-allowed',
          variants[variant],
          sizes[size],
          className
        )}
        {...props}
      >
        {loading && (
          <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
        )}
        {children}
      </button>
    );
  }
);
Button.displayName = 'Button';

// nxt-web/src/lib/components/ui/Button.svelte
<script lang="ts" module>
	export type ButtonVariant = 'primary' | 'gold' | 'navy' | 'outline' | 'ghost' | 'glass';
	export type ButtonSize = 'sm' | 'md' | 'lg';
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils/cn';

	type Props = {
		variant?: ButtonVariant;
		size?: ButtonSize;
		href?: string;
		loading?: boolean;
		class?: string;
		children: Snippet;
	} & Partial<HTMLButtonAttributes & HTMLAnchorAttributes>;

	let {
		variant = 'primary',
		size = 'md',
		href,
		loading = false,
		class: cls,
		children,
		...rest
	}: Props = $props();

	const variants: Record<ButtonVariant, string> = {
		primary:
			'bg-primary text-primary-fg shadow-lg shadow-primary/25 hover:bg-primary-deep hover:shadow-primary/40',
		gold: 'bg-gold text-navy shadow-lg shadow-gold/30 hover:brightness-105',
		navy: 'bg-navy text-white hover:bg-navy-soft',
		outline: 'border border-outline-soft text-ink hover:border-primary hover:text-primary bg-transparent',
		ghost: 'text-ink hover:bg-card',
		glass: 'glass border border-white/40 text-navy hover:bg-white/80'
	};
	const sizes: Record<ButtonSize, string> = {
		sm: 'h-9 px-4 text-sm gap-1.5',
		md: 'h-11 px-6 text-sm gap-2',
		lg: 'h-13 px-8 text-base gap-2.5'
	};

	const base =
		'group relative inline-flex items-center justify-center rounded-full font-semibold transition-all duration-300 ease-[cubic-bezier(0.16,1,0.3,1)] active:scale-[0.97] disabled:opacity-50 disabled:pointer-events-none whitespace-nowrap';
</script>

{#if href}
	<a {href} class={cn(base, variants[variant], sizes[size], cls)} {...rest}>
		{#if loading}<span class="mr-1 size-4 animate-spin rounded-full border-2 border-current border-t-transparent"></span>{/if}
		{@render children()}
	</a>
{:else}
	<button class={cn(base, variants[variant], sizes[size], cls)} disabled={loading || rest.disabled} {...rest}>
		{#if loading}<span class="mr-1 size-4 animate-spin rounded-full border-2 border-current border-t-transparent"></span>{/if}
		{@render children()}
	</button>
{/if}
