// admin-panel/src/routes/(app)/users/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import Topbar from '$lib/components/Topbar.svelte';
  import Card from '$lib/components/Card.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import { formatDate } from '$lib/format';
  import { Search, Trash2 } from 'lucide-svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
  const roles = ['buyer', 'owner', 'broker', 'admin'];
  const tone = (r: string) => (r === 'admin' ? 'danger' : r === 'broker' ? 'info' : r === 'owner' ? 'warning' : 'neutral');
</script>

<Topbar title="Users" subtitle={`${data.items.length} accounts`} name={data.session?.name ?? 'Admin'} />

<div class="space-y-5 p-6">
  <form method="GET" class="flex flex-wrap items-center gap-3">
    <div class="relative min-w-[240px] flex-1">
      <Search size={16} class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
      <input name="search" value={data.filters.search} placeholder="Search name or email…" class="input pl-9" />
    </div>
    <select name="role" value={data.filters.role} class="input max-w-[180px]">
      <option value="">All roles</option>
      {#each roles as r}<option value={r}>{r}</option>{/each}
    </select>
    <button class="btn-primary">Filter</button>
  </form>

  <Card class="p-0 overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="border-b border-line text-left text-xs uppercase tracking-wider text-slate-500">
          <tr><th class="px-5 py-3">User</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Joined</th><th class="px-5 py-3 text-right">Actions</th></tr>
        </thead>
        <tbody class="divide-y divide-line">
          {#each data.items as u}
            <tr class="hover:bg-panel2/50">
              <td class="px-5 py-3">
                <div class="font-medium text-slate-100">{u.name ?? 'User'}</div>
                <div class="text-xs text-slate-500">{u.email ?? u.phone ?? '—'}</div>
              </td>
              <td class="px-5 py-3">
                <div class="flex items-center gap-2">
                  <Badge tone={tone(u.role)}>{u.role}</Badge>
                  {#if u.verifiedBroker}<Badge tone="success">RERA</Badge>{/if}
                </div>
              </td>
              <td class="px-5 py-3 text-slate-400">{formatDate(u.createdAt)}</td>
              <td class="px-5 py-3">
                <div class="flex items-center justify-end gap-2">
                  <form method="POST" action="?/setRole" use:enhance>
                    <input type="hidden" name="id" value={u.userId} />
                    <select name="role" class="input w-[120px] py-1.5" onchange={(e) => (e.currentTarget.form as HTMLFormElement).requestSubmit()}>
                      {#each roles as r}<option value={r} selected={r === u.role}>{r}</option>{/each}
                    </select>
                  </form>
                  <form method="POST" action="?/toggleBroker" use:enhance>
                    <input type="hidden" name="id" value={u.userId} />
                    <input type="hidden" name="verified" value={(!u.verifiedBroker).toString()} />
                    <button class="btn-ghost px-3 py-1.5 text-xs">{u.verifiedBroker ? 'Unverify' : 'Verify broker'}</button>
                  </form>
                  <form method="POST" action="?/delete" use:enhance>
                    <input type="hidden" name="id" value={u.userId} />
                    <button class="btn-ghost px-2.5 py-1.5" title="Delete" onclick={(e) => !confirm('Delete this user?') && e.preventDefault()}>
                      <Trash2 size={15} color="#fb7185" />
                    </button>
                  </form>
                </div>
              </td>
            </tr>
          {/each}
          {#if data.items.length === 0}<tr><td colspan="4" class="px-5 py-12 text-center text-slate-500">No users found</td></tr>{/if}
        </tbody>
      </table>
    </div>
  </Card>
</div>

// admin-panel/app/(admin)/users/page.tsx
export const dynamic = 'force-dynamic';
import { createAdminClient } from '@/lib/supabase/server';
import { Topbar } from '@/components/layout/topbar';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { UserActions } from '@/components/users/user-actions';
import { formatDate } from '@/lib/utils';
import { Users } from 'lucide-react';

async function getUsers(search?: string, role?: string) {
  const supabase = createAdminClient();
  let query = supabase
    .from('users_profiles')
    .select('*')
    .order('created_at', { ascending: false });

  if (search) {
    query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
  }
  if (role && role !== 'all') {
    query = query.eq('role', role);
  }

  const { data, error } = await query.limit(200);
  return data || [];
}

export default async function UsersPage({
  searchParams,
}: {
  searchParams: Promise<{ search?: string; role?: string }>;
}) {
  const params = await searchParams;
  const users = await getUsers(params.search, params.role);

  const roleCounts = users.reduce((acc, u) => {
    acc[u.role] = (acc[u.role] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return (
    <div>
      <Topbar title="Users" subtitle={`${users.length} total users`} />

      <div className="p-6 space-y-6">
        {/* Role Summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {['buyer', 'owner', 'broker', 'admin'].map((role) => (
            <Card key={role} className="p-4">
              <p className="text-2xl font-bold text-white">{roleCounts[role] || 0}</p>
              <p className="text-xs text-gray-500 mt-1 capitalize">{role}s</p>
            </Card>
          ))}
        </div>

        {/* Filters */}
        <Card className="p-4">
          <form className="flex flex-wrap gap-3">
            <input
              name="search"
              defaultValue={params.search}
              placeholder="Search by name or email..."
              className="flex-1 min-w-[200px] rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#FF6B35] focus:border-transparent"
            />
            <select
              name="role"
              defaultValue={params.role || 'all'}
              className="rounded-lg bg-gray-800 border border-gray-700 px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-[#FF6B35]"
            >
              <option value="all">All Roles</option>
              <option value="buyer">Buyer</option>
              <option value="owner">Owner</option>
              <option value="broker">Broker</option>
              <option value="admin">Admin</option>
            </select>
            <button
              type="submit"
              className="px-4 py-2 bg-[#FF6B35] text-white text-sm rounded-lg hover:bg-[#e55a25] transition-colors"
            >
              Search
            </button>
          </form>
        </Card>

        {/* Table */}
        <Card className="p-0 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-800">
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">User</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Role</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Phone</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Joined</th>
                  <th className="text-left px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="text-right px-6 py-4 text-xs font-semibold text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                {users.map((user: any) => (
                  <tr key={user.user_id} className="hover:bg-gray-800/50 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-full bg-[#FF6B35]/20 flex items-center justify-center text-[#FF6B35] text-sm font-bold flex-shrink-0">
                          {user.name?.charAt(0)?.toUpperCase() || '?'}
                        </div>
                        <div>
                          <p className="text-sm font-medium text-white">{user.name}</p>
                          <p className="text-xs text-gray-500">{user.email}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <Badge
                        variant={
                          user.role === 'admin' ? 'danger' :
                          user.role === 'broker' ? 'info' :
                          user.role === 'owner' ? 'warning' : 'secondary'
                        }
                      >
                        {user.role}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-400">{user.phone || '—'}</td>
                    <td className="px-6 py-4 text-sm text-gray-400">{formatDate(user.created_at)}</td>
                    <td className="px-6 py-4">
                      {user.verified_broker ? (
                        <Badge variant="success">Verified Broker</Badge>
                      ) : (
                        <Badge variant="secondary">Standard</Badge>
                      )}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <UserActions
                        userId={user.user_id}
                        currentRole={user.role}
                        isVerifiedBroker={user.verified_broker}
                      />
                    </td>
                  </tr>
                ))}
                {users.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-6 py-12 text-center">
                      <Users className="w-10 h-10 text-gray-700 mx-auto mb-3" />
                      <p className="text-gray-500 text-sm">No users found</p>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </Card>
      </div>
    </div>
  );
}
